name: durl
description: A curl-like Discord command line client.
version: 1.1.0

environment:
  sdk: '>=2.18.2 <3.0.0'

executables:
  durl:

dependencies:
  args: ^2.3.1
  http: ^0.13.5
  shelf: ^1.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
